### ISSUE TITLE
VM creation takes too long for unavailable VM type

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/bosh-aws-cpi-release#102]
The task log below shows that instance creation for an unavailable VM type took around 5 and a half hours.

```
Task 2113648

Task 2113648 | 07:14:04 | Preparing deployment: Preparing deployment (00:00:02)
Task 2113648 | 07:14:06 | Preparing deployment: Rendering templates (00:00:02)
Task 2113648 | 07:14:08 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 2113648 | 07:14:08 | Updating instance postgresql: postgresql/4d4565cd-0acd-40b8-b095-1ae876f89198 (0) (canary) (05:31:52)
                     L Error: Unknown CPI error 'Unknown' with message 'We currently do not have sufficient m4.4xlarge capacity in the Availability Zone you requested (<some-zone>). Our system will be working on provisioning additional capacity. You can currently get m4.4xlarge capacity by not specifying an Availability Zone in your request or choosing <some-zone>, <some-zone>.' in 'create_vm' CPI method (CPI request ID: 'cpi-789250')
Task 2113648 | 12:46:00 | Error: Unknown CPI error 'Unknown' with message 'We currently do not have sufficient m4.4xlarge capacity in the Availability Zone you requested (<some-zone>). Our system will be working on provisioning additional capacity. You can currently get m4.4xlarge capacity by not specifying an Availability Zone in your request or choosing <some-zone>, <some-zone>.' in 'create_vm' 




CPI method (CPI request ID: 'cpi-789250')

Task 2113648 Started  Tue Nov 26 07:14:04 UTC 2019
Task 2113648 Finished Tue Nov 26 12:46:00 UTC 2019
Task 2113648 Duration 05:31:56
Task 2113648 error

Capturing task '2113648' output:
  Expected task '2113648' to succeed but state is 'error'

Exit code 1
```

In the debug logs of this task  we see that the AWS SDK retries 16 times and this takes about 5 hours:

```
D, [2019-11-26T07:18:10.541852 #102165] [create_missing_vm(postgresql/4d4565cd-0acd-40b8-b095-1ae876f89198 (0)/1)] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-789250] request: {"method":"create_vm"...
D, [2019-11-26T12:46:00.806718 #102165] [create_missing_vm(postgresql/4d4565cd-0acd-40b8-b095-1ae876f89198 (0)/1)] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-789250] response: {"result":null,"error":{"type":"Unknown","message":"We currently do not have...
D, [2019-11-26T12:46:00.797137 #102572] DEBUG -- [req_id cpi-789250]: [Aws::EC2::Client 500 19668.571233 16 retries] run_instances(image_id:"ami-0ffd3828a484a9b06",instance_type:"m4.4xlarge"
E, [2019-11-26T12:46:00.797405 #102572] ERROR -- [req_id cpi-789250]: Failed to create instance: We currently do not have sufficient m4.4xlarge capacity in the Availability Zone...
I, [2019-11-26T12:46:00.797717 #102572]  INFO -- [req_id cpi-789250]: Finished create_vm in 19669.06 seconds
```

**Expected behaviour:**
The task fails after the first try provisioning an unavailable vm_type.

cc 
@BeckerMax @friegger

**Comment by ssapra** [comment]
Did it take 16 retries because you had set `aws.max_retries` in the CPI properties? The configuration from https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/master/jobs/aws_cpi/spec#L49 is used for EC2 client's `retry_limit`.

I believe the retry logic is meant to help in the situation that the instance type becomes available after a short period of time. 

Looking at the [list of server errors](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html), the response to `run_instances` could be checked for an error like `InsufficientInstanceCapacity` or similar error codes. 

If this is something you think should be added to the CPI, please submit a PR and we can review it. 

Thanks!

**Comment by friegger** [comment]
@ssapra `aws.max_retries` is set to `8`. Not sure why it did 16 tries.
Exactly it should not retry on `InsufficientInstanceCapacity`. Thanks for checking this. We'll consider providing a PR.

**Comment by beyhan** [comment]
After further investigations into this issue we found out that the `retry_limit` (https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/master/jobs/aws_cpi/spec#L49) is working as expected and could be used to control the waiting time for unavailable resources. At the moment we don't see a need to handle `InsufficientInstanceCapacity` exceptions differently.
