### ISSUE TITLE
m5n and m5dn instance types are not supported

### ISSUE THREAD

**Issue by h4xnoodle** [cloudfoundry/bosh-aws-cpi-release#103]
The instance type list is out of date

https://aws.amazon.com/ec2/instance-types/

**Comment by voelzmo** [comment]
More specifically: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances

**Comment by h4xnoodle** [comment]
@voelzmo do you then expect all instance types to be in the list?

While I'm tempted to add all types, this essentially means they'll be untested. `m5n` and `m5dn` I tested with yesterday. I'll add them all but I don't think we can guarantee they all work perfectly. I'll try deploying at least one from each 'category', I suppose.

**Comment by voelzmo** [comment]
> @voelzmo do you then expect all instance types to be in the list?

I'm not sure what the test process looks like for these instances. My understanding was that the CPI maintains a list of nitro-based VM types in AWS and the link above points to that list.

In this specific issue, we were mostly concerned with the `m5dn` instances, but I think your change makes sense. If other issues exist which make these instance types unusable, they're at least visible now and could be fixed individually.

Thanks, @h4xnoodle!
