### ISSUE TITLE
Support for 6th generation of AWS instance types

### ISSUE THREAD

**Issue by sebarys** [cloudfoundry/bosh-aws-cpi-release#108]
Hello everyone!

Is it planned support for 6th generation of AWS instance types e.g. https://aws.amazon.com/ec2/instance-types/m6/ ?

Regards

**Comment by dsboulder** [comment]
Have you tried these yet? For example, 4th generation instance types just worked. Some 5th generation types also just worked, but others required some NVMe changes on the stemcell. Would you be able to help us validate if 6th generation types boot normally?

**Comment by ystros** [comment]
We added NVMe support for the `m6g` and `m6gd` instance types in CPI version 85.
