### ISSUE TITLE
Support for r6g instance type

### ISSUE THREAD

**Issue by soroshidg** [cloudfoundry/bosh-aws-cpi-release#115]
It seems current supported VM type is not supporting r6g instance type. https://aws.amazon.com/ec2/instance-types/r6/

**Comment by camilalonart** [comment]
The supported VM types are only general purpose VMs, R6g is ARM and would not work for most deployments. If you want to use the R6g instance type, you can specify it as the instance type in your cloud config, check this link for more info https://bosh.io/docs/aws-cpi/#resource-pools
