### ISSUE TITLE
hardcoded timeout for native resize operation is too low

### ISSUE THREAD

**Issue by jsievers** [cloudfoundry/bosh-aws-cpi-release#116]
We tried resizing a persistent disk from 2TB to 4 TB with recent changes provided in

https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/109

It turns out the hardcoded timeout of ~ 25 minutes for the volume modification is too low:

```
Task 3553 | 14:23:52 | Preparing deployment: Preparing deployment (00:00:01)
Task 3553 | 14:23:53 | Preparing deployment: Rendering templates (00:00:00)
Task 3553 | 14:23:53 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 3553 | 14:23:53 | Updating instance hcpbd-aws-dev06-grafana: hcpbd-aws-dev06-grafana/152cc1a2-dec3-4a6d-9a52-5f4b5b2738cf (0) (canary) (00:27:25)
                     L Error: CPI error 'Bosh::Clouds::CloudError' with message 'Timed out waiting for volume modification of vol-0c10bf05a1f8b26b2 current state modifying to be completed, took 1602.672011737s' in 'resize_disk' CPI method (CPI request ID: 'cpi-550813')
Task 3553 | 14:51:18 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'Timed out waiting for volume modification of vol-0c10bf05a1f8b26b2 current state modifying to be completed, took 1602.672011737s' in 'resize_disk' CPI method (CPI request ID: 'cpi-550813')

Task 3553 Started  Fri Oct  8 14:23:52 UTC 2021
Task 3553 Finished Fri Oct  8 14:51:18 UTC 2021
Task 3553 Duration 00:27:26
Task 3553 error

Capturing task '3553' output:
  Expected task '3553' to succeed but state is 'error'
```

A simple fix would be to increase the timeout just for the volume modification to be 4 times the default timeout. I will create a PR for this.

One could also argue the timeout should be configurable but that's a bigger change I guess.

**Comment by jsievers** [comment]
this was fixed with merging #117 

do you have an ETA on when the next release would be available?

**Comment by bgandon** [comment]
Sort of, as merging #117 is a valuable quick fix for the time being. But we need `v90` to be cut.

In the meantime, I still have pending work for a configurable timeout scale factor as announced in https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/117#issuecomment-946748662

Vacations and other priorities have made it harder to come up. I'll push that to some PR soon hopefully.

**Comment by cunnie** [comment]
Closing. V90 was released 7 days. Unless you were looking for additional fixes, we believe we have addressed this issue.

**Comment by bgandon** [comment]
Yes indeed 👍 and this timeout has been obsoleted in #123 shipped with [v92](https://github.com/cloudfoundry/bosh-aws-cpi-release/releases/tag/v92).
