### ISSUE TITLE
m6i missing from NVME_INSTANCE_FAMLIES

### ISSUE THREAD

**Issue by blyles** [cloudfoundry/bosh-aws-cpi-release#120]
NVME_INSTANCE_FAMILIES = %w[a1 c5 c5a c5ad c5d c5n c6g c6gd c6gn d3 d3en g4 i3en inf1 m5 m5a m5ad m5d m5dn m5n m5zn m6g m6gd p3dn p4 r5 r5a r5ad r5b r5d r5dn r5n r6g r6gd t3 t3a t4g z1d].freeze

m6i missing from the block_device_manager.rb

# Newer, nitro-based instances use NVMe storage volumes.
    # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances

**Comment by rkoster** [comment]
@blyles The fasts way to get this fixed would be to create a PR.

**Comment by blyles** [comment]
@rkoster can't seem to create branch/pr? Im missing something aren't i?

**Comment by blyles** [comment]
@rkoster  👍   - https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/121

**Comment by rkoster** [comment]
https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/121 Got merged
