### ISSUE TITLE
Speed up native EBS volume resizing

### ISSUE THREAD

**Issue by swlotzka** [cloudfoundry/bosh-aws-cpi-release#122]
The current implementation waits until the volume modification state has reached `completed` [1]. I think this is unnecessarily long.

Quotes of the documentation [2]:
* The volume enters the modifying state, the optimizing state, and finally the completed state
* Size changes usually take a few seconds to complete and take effect after the volume has transitioned to the Optimizing state
* While the volume is in the optimizing state, your volume performance is in between the source and target configuration specifications. [...]
* Performance (IOPS) changes can take from a few minutes to a few hours to complete [...]

In total, this sounds to me that we only need to wait until the optimizing state is started. The disk will be fully functional. Only the IOPS would be adjusted in the background, if changed (explicitly per request, or implicitly, e.g. for gp2 disks [3]), while preserving IO performance.
We could let the operator choose between the current waiting behavior or the one proposed here.

[1] https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/4489ae81ac9428cb2ba3f14b0a07f4a5980b8ff0/src/bosh_aws_cpi/lib/cloud/aws/sdk_helpers/volume_manager.rb#L29
[2] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-volume-modifications.html
[3] https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyVolume.html

**Comment by bgandon** [comment]
I've pushed in #123 some implementation for a solution to this issue.

**Comment by beyhan** [comment]
This has been implemented in https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/123 and there is a release already which includes this change: https://github.com/cloudfoundry/bosh-aws-cpi-release/releases/tag/v92.
