### ISSUE TITLE
Support GP3 IOPS and MB/S configuration parameters

### ISSUE THREAD

**Issue by schmidtsv** [cloudfoundry/bosh-aws-cpi-release#125]
Hello cpi team,

I wanted to ask if you plan to support the gp3 parameters for provisioning throughput and iops in the near future. We are in a bind because we have cases where the default throughput is not enough, but we would like to avoid having go io1 to avoid the disk credit trap.

**Comment by schmidtsv** [comment]
Was bored. Wrote it myself: #126

**Comment by schmidtsv** [comment]
For reference. I also wrote a PR for the bosh docs that can be merged once a release is built with iops and mbp/s abilities 
https://github.com/cloudfoundry/docs-bosh/pull/762

**Comment by rkoster** [comment]
#126 has been merged and has been shipped in: https://github.com/cloudfoundry/bosh-aws-cpi-release/releases/tag/v93
