### ISSUE TITLE
Make AWS keypair optional

### ISSUE THREAD

**Issue by bengerman13** [cloudfoundry/bosh-aws-cpi-release#128]
Currently, the cpi [requires the name of a key pair in EC2](https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/master/jobs/aws_cpi/spec#L32-L34).
AWS also does not require this key pair, and we can tell BOSH isn't leveraging it (because it doesn't ask for the private key ever), so there's no need for it. Including one represents a minor security concern, because it's one more access key to rotate or that could get lost. 
We'd like to remove this as a required field if at all possible

**Comment by rkoster** [comment]
This sounds like a good improvement, do you happen to know since when AWS stopped requiring a key_pair on VM creation?

**Comment by rkoster** [comment]
Seems like it was made required in 2013 in the cpi codebase: https://github.com/cloudfoundry/bosh-aws-cpi-release/commit/3eab961790a330bae1b915f2afe7595175c47c57
At least the validation was added back then.
