### ISSUE TITLE
Request new feature to register bosh managed vm with LB by IP (vs instance_id).

### ISSUE THREAD

**Issue by Houlistonm** [cloudfoundry/bosh-aws-cpi-release#130]
This is resurrecting issue #92 .
We're having the same issue.

The capability to pass these properties to the connection would be beneficial: [link](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#:~:text=unable%20to%20respond.-,Target%20group%20attributes,-The%20following%20are)

The `preserve_client_ip.enabled` property is required to answer a security auditing requirement.

I'm available in vmware slack.

**Comment by rkoster** [comment]
@Houlistonm have you been able to test the workaround as suggested by @nouseforaname?

**Comment by nouseforaname** [comment]
After doing some more investigation on the troubled environment, we found that adding this functionality would not help. We're closing this out in favor of another approach that does not require updates to the cpi
