### ISSUE TITLE
heavy(full) stemcell cannot be used with create-env

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh-aws-cpi-release#134]
it seems that trying to use a full stemcell with `bosh create-env` it tries to connect to the metadata server from the localhost.
which ofcourse cannot be reached.

**Comment by ramonskie** [comment]
more info on this @friegger

**Comment by friegger** [comment]
We've seen various errors, even when running `create-env` from EC2 instances, like:
```
CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Cannot find EBS volume on current instance","ok_to_retry":false}
```

or 

```
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Timed out reading instance metadata, please make sure CPI is running on EC2 instance","ok_to_retry":false}
```

We will instead create a light stemcell before hand, as this does not seem trivial to solve.

**Comment by rkoster** [comment]
Heavy stemcell require access to mounted disks to be able to copy over the stemcell contents using: https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/master/src/bosh_aws_cpi/bin/stemcell-copy

As discussed during working group sync meeting, in this case bosh create-env was run inside a container without access to mounted disks.
