### ISSUE TITLE
Add missing c6i to NVMe instances

### ISSUE THREAD

**Issue by keviningvalson** [cloudfoundry/bosh-aws-cpi-release#135]
similar to https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/121 c6i needs to be added.

**Comment by ramonskie** [comment]
we would gladly accept a PR for this

**Comment by keviningvalson** [comment]
https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/136 has been submitted
