### ISSUE TITLE
Add AWS Gen6 AMD instance Types To AWS Block Device Manager code

### ISSUE THREAD

**Issue by burgerjeffrey** [cloudfoundry/bosh-aws-cpi-release#142]
Code is missing r6a, m6a and c6a instance types from AWS.  
BOSH will not deploy vm's that have persistent EBS volumes to these new instance types currently.

https://github.com/cloudfoundry/bosh-aws-cpi-release/blob/master/src/bosh_aws_cpi/lib/cloud/aws/block_device_manager.rb#L8

**Comment by blyles** [comment]
https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/143

**Comment by ramonskie** [comment]
closed as #143 is merged
