### ISSUE TITLE
BOSH Agent not reachable due to issues with blobstore settings

### ISSUE THREAD

**Issue by anshrupani** [cloudfoundry/bosh-aws-cpi-release#149]
We identified some issues with the recent CPI version bumps, where the agent is not able to start due to missing blobstore properties. We guess these issues might have been triggered by #147.

On the outside, we see the following while deploying the director:
```
Deploying:
Creating instance 'bosh/0':
  Waiting until instance is ready:
    Post "https://mbus:<redacted>@<director-hostname>:6868/agent": dial tcp <director-ip>:6868: connect: connection refused
```

Here's what we observed in the agent logs on the director VM:
```
2023-04-27_14:38:07.96970 [main] 2023/04/27 14:38:07 ERROR - App setup Getting blobstore: Getting blobstore: Validating blobstore: executable bosh-blobstore- not found in PATH
2023-04-27_14:38:07.96971 [main] 2023/04/27 14:38:07 ERROR - Agent exited with error: Getting blobstore: Getting blobstore: Validating blobstore: executable bosh-blobstore- not found in PATH
```

The settings.json, on the other hand consists the following, which might be expected:
`{{"blobstore":{"provider":"","options":null} }}`

We observe this on AWS and GCP bosh-cpi releases (version 98 and 47 respectively). Azure (v44) also most probably has the issue, but we did not test it yet.

**Comment by beyhan** [comment]
I think what happens is that in `create-env` the bosh-cli is using [this properties](https://github.com/cloudfoundry/bosh-deployment/blob/c62c8bd8265cef7534ba03d6c012601476304d87/bosh.yml#L4-L9) to configure the blobstore. The `env` in the `settings.json` is available for the VMs created by bosh directore [see](https://github.com/cloudfoundry/bosh/blob/aed512b765acaa6721df87be7584599f00fdf3f9/src/bosh-director/lib/bosh/director/deployment_plan/steps/create_vm_step.rb#L105-L145). I think that `create-env` doesn't populate the `env` that is why after the removal [in](https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/147) the blobstore properties are missing.

**Comment by beyhan** [comment]
Ok, somehow I missed the `reasource_pools` option for `bosh create-env`. Good to know. In this case we should clean up the bosh.yml manifest in bosh-deployment. I created this [pr](https://github.com/cloudfoundry/bosh-deployment/pull/449). Or is there any other reason to keep blobstore properties under `cloud_provider`?

**Comment by anshrupani** [comment]
Oh, thanks @beyhan and @ystros for pointing out the issue :)
We have indeed not updated our manifests. We will test it out and provide feedback soon.

**Comment by ramonskie** [comment]
@anshrupani can we close this issue?

**Comment by anshrupani** [comment]
Hi @ramonskie, @beyhan
We were blocked in our testing due to other issues, but we can confirm that suggestions provided by @ystros help.
We'll close the issue now.
