### ISSUE TITLE
Disable Metadata API v1

### ISSUE THREAD

**Issue by scult** [cloudfoundry/bosh-aws-cpi-release#156]
Hi there,

we got an AWS Security Best Practices finding that the Instance Metadata Service Version 1 (IMDSv1) should be disabled in favor of only supporting Instance Metadata Service Version 2 (IMDSv2). It turns out that this is configured during VM creating, or in this case of bosh stemcells baked into the AMI. Currently it looks like this isn't configured in the stemcell at all so it defaults to supporting both API versions.

Are there any plans for disabling IMDSv1 for the AWS stemcells in the future?

**Comment by jpalermo** [comment]
Was this already done here? https://github.com/cloudfoundry/bosh-aws-cpi-release/commit/3876adcd41f947264e7dc1b2eb2ecc2e7d8a893a

**Comment by beyhan** [comment]
@scult could you please check whether the linked commit above works for you? If yes, we are happy to review a docs pr for it because it seems that the documentation was missed.

**Comment by scult** [comment]
That worked, thank you very much for your help

**Comment by jpalermo** [comment]
For anybody following up on this issue later, I believe the configuration needed to require IMDSv2 is configuring the `aws.metadata_options` property of the CPI with `{ 'http_tokens' => 'required' }`
