### ISSUE TITLE
Missing snapshots cause repeated orphan disk cleanup retries

### ISSUE THREAD

**Issue by dpb587** [cloudfoundry/bosh-aws-cpi-release#35]
I'm not entirely sure if this is a director issue or a CPI issue, but... when deleting a snapshot fails, it bubbles up to the director as an unknown error...

```
{ "result": null,
  "error": {
    "type": "Unknown",
    "message":"The snapshot 'snap-a1b2c3d4' does not exist.",
    "ok_to_retry": false ...
```

Long-standing behavior, but with the introduction of orphan disks this becomes much more noticeable. The every-30-minute cron job continuously retries deleting the same snapshot indefinitely. This leads to excess orphan disks hanging around and can easily fill up the ~FIFO task log history if unnoticed. I think the only workaround is manually deleting the snapshot entry from the database.

In the case of deleting disks, director will [rescue](https://github.com/cloudfoundry/bosh/blob/695bed549bd93dd263285b6da08b4c23fe24e98c/bosh-director/lib/bosh/director/disk_manager.rb#L133) the `Bosh::Clouds::DiskNotFound` error that cpi [raises](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/e54055cde09a6fdc2097dd8ab54de66baa9ae42c/src/bosh_aws_cpi/lib/cloud/aws/cloud.rb#L262) and always destroy the entry from the database.

In the case of deleting snapshots, director will [rescue](https://github.com/cloudfoundry/bosh/blob/695bed549bd93dd263285b6da08b4c23fe24e98c/bosh-director/lib/bosh/director/disk_manager.rb#L217) the same (?) `Bosh::Clouds::DiskNotFound` error, but cpi [doesn't raise](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/e54055cde09a6fdc2097dd8ab54de66baa9ae42c/src/bosh_aws_cpi/lib/cloud/aws/cloud.rb#L378) for that case so the generic error is thrown and director doesn't know what to do.

**Comment by dpb587** [comment]
Also, not exactly sure where the snapshot disappeared to in my case. Pretty sure I've only been deleting bosh disk snapshots via bosh cli/api. Just weird and probably unrelated. Still seems like a reasonable bug/scenario to avoid.

**Comment by dpb587-pivotal** [comment]
Briefly discussed this at the office. A proposed fix was to create a new error class in `bosh_cpi` (SnapshotNotFound to match DiskNotFound), update director to catch that error and clean up the db, and make this repo catch the sdk error to re-raise as SnapshotNotFound.
