### ISSUE TITLE
Get a release compilation error with new bosh create-env cli command. 

### ISSUE THREAD

**Issue by nsagoo-pivotal** [cloudfoundry/bosh-aws-cpi-release#45]
I received a gcc compilation error when creating a new Bosh director using the new Bosh cli. Workaround used: https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91
Please update bosh documentation as it was unclear the necessary steps for beginning a Director deployment needs to have OS specific deps: http://bosh.io/docs/install-bosh-init

bosh create-env ./bosh.yaml
Deployment manifest: '/Users/nsagoo/Workspace/bosh/bosh.yaml'
Deployment state: '/Users/nsagoo/Workspace/bosh/bosh-state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bosh-aws-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-aws-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:01)

Started installing CPI
  Compiling package 'ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042'... Failed (00:00:01)
Failed installing CPI (00:00:01)

Installing CPI:
  Compiling job package dependencies for installation:
    Compiling job package dependencies:
      Compiling package:
        Running command: 'bash -x packaging', stdout: 'Installing yaml
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... config/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... no
checking for gcc... gcc
checking whether the C compiler works... no
', stderr: '+ set -e -x
++ PATH=/usr/local/opt/openssl/bin:/usr/local/bin:/usr/bin:/bin
++ openssl version
+ openssl_version='OpenSSL 1.0.2h  3 May 2016'
++ echo OpenSSL 1.0.2h 3 May 2016
++ cut -f2 '-d '
++ cut -f1 -d.
+ openssl_major_version=1
+ '[' 1 == 0 ']'
+ echo 'Installing yaml'
+ tar xzf ruby_aws_cpi/yaml-0.1.5.tar.gz
+ pushd yaml-0.1.5
+ CFLAGS=-fPIC
+ ./configure --prefix=/Users/nsagoo/.bosh/installations/30403ef4-3e2a-44e8-45fb-c101bbd5c86f/packages/ruby_aws_cpi --disable-shared
configure: error: in `/Users/nsagoo/.bosh/installations/30403ef4-3e2a-44e8-45fb-c101bbd5c86f/tmp/bosh-release-pkg315473132/yaml-0.1.5':
configure: error: C compiler cannot create executables
See `config.log' for more details
':
          exit status 77

Exit code 1

**Comment by ljfranklin** [comment]
@nsagoo-pivotal thanks for opening this issue. Threw [this story](https://www.pivotaltracker.com/story/show/137281827) in our Icebox, we'll try to pull it into the Backlog soon.
