### ISSUE TITLE
Support for EBS-optimisation setting on non optimised instances

### ISSUE THREAD

**Issue by dmlemos** [cloudfoundry/bosh-aws-cpi-release#53]
When an EBS-optimised instance is configured in the manifest, the instance is launched without taking into account this property! I noticed afterwords the EBS-optimised setting in the AWS EC2 instances panel is not activated.
The list of supported instances is here:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html#ebs-optimization-support

Launching the stemcell AMI directly in AWS sets this automatically (although it is just visual - read below).

Apparently it has no effect if the instance launched is from the list above, as quoted from the link:
"Note that some instance types are EBS–optimized by default. For instances that are EBS–optimized by default, there is no need to enable EBS optimization and there is no effect if you disable EBS optimization using the CLI or API. You can enable EBS optimization for the other instance types that support EBS optimization when you launch the instances, or enable EBS optimization after the instances are running."
The optimisation is automatically enabled without any additional cost.

Now, in the case of **non-optimised instances** they could take advantage of this feature.

Found a good explanation of this setting:
https://dzone.com/articles/when-amazon-ebs-optimized

Tested with AWS CPI `v63`

Discussion on slack:
https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1492531440364851

**Comment by cdutra** [comment]
Hi @dmlemos , this feature makes sense. Would you like to make a PR for it?

**Comment by blyles** [comment]
From what we can tell this issue never got resolved? seems the bosh cpi doesn't work with the optimization and through the UI/UX from amazon it does.  Was there a reason this was abandoned?
