### ISSUE TITLE
Improve cpi error handling

### ISSUE THREAD

**Issue by sklevenz** [cloudfoundry/bosh-aws-cpi-release#59]
I did hit a api rate limit at AWS and received this error message from CPI:

"Unknown CPI error 'Unknown' with message 'Request limit exceeded.' in 'create_vm' CPI method (00:01:26) "

AWS says: "If an API request exceeds the API request rate for its category, the request returns the RequestLimitExceeded error code." (http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html)

So, I think the CPI error is not unknown. Instead I suggest that the CPI should return "equestLimitExceeded error code" additionally to the text message.

WDYT?

**Comment by cppforlife** [comment]
@sklevenz i think it's showing unknown from a perspective of director. in the director there are several types of errors that are expected from cpis. might make sense for aws to return generic CloudError for more errors like this one.
