### ISSUE TITLE
Bosh - creating an aws instance - merge two calls into one

### ISSUE THREAD

**Issue by venkatasajja** [cloudfoundry/bosh-aws-cpi-release#62]
we are currently using bosh version 262.3. The question I have is on how bosh provisions
ec2 instances in AWS through bosh-aws-cpi. 

To give a little context on how provisioning on AWS used to happen 

In March, AWS Blog announced two new features we’re implementing:
Ability to enforce required tags on RunInstances with IAM policy
Ability to include tags on RunInstances with API and CLI 

Which means, before this date all provisioning was done in two steps:

ec2 run-instances --image-id <ami-id> --count 1 --instance-type t2.micro --subnet-id
<subnet-id>

ec2-create-tags <instanceid> --tag "Name=<name_value>" --tag
"App=<app_value>" --tag "AppOwner=<app_owner_value>" --tag
"Environment=<env_value>"

The new workflow assured that instance creation and tag management can be done in a single
call. 

ec2 run-instances --image-id <ami-id> --count 1 --instance-type t2.micro --subnet-id
<subnet-id> --tag-specifications
'ResourceType=instance,Tags=[{Key=Name,Value=<name_value>},{Key=App,Value=<app_value>},{Key=AppOwner,Value=<app_owner_value>},{Key=Environment,Value=<env_value>}]'

Bosh ( tested with version 262.3 ) still seem to be provisioning instances in multiple
calls instead of a single one. Bosh is issuing 1 api call just to create the instance, and
then following that up with a 2nd api call to create-tags.

**Comment by cdutra** [comment]
@venkatasajja To make on single API is a specific use case for AWS (not sure if other IaaSs would benefit from that). Also separate calls make BOSH Director enable to update vm metadata without calling the create_vm again therefore no need for deleting the VM.
Your use case could be implemented in the `create_vm` by exposing properties to set `startup_tags` or somethings like that.
This would fulfill both use cases.

**Comment by cdutra** [comment]
@cppforlife Any thoughts on that? This opens up for a finer grain resource-level permission management if we allow users to tag vms on creation.

https://aws.amazon.com/blogs/aws/new-tag-ec2-instances-ebs-volumes-on-creation/

**Comment by thiezn** [comment]
This would be a great feature to have. We rely on tags for event based corrective security controls and having the tags available on RunInstances/StartInstances events would remove a lot of boiler plate code and potential race conditions.
