### ISSUE TITLE
proposal: add a tag to vms to document the cloud-config vm_type used

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-aws-cpi-release#68]
When looking at the AWS console, we can see the AWS instance type but cannot see the `bosh cloud-config` vm_type. And in `bosh instances` we see the reverse.

Could the AWS CPI create an additional tag `vm_type` to document which cloud-config vm_type was used?

**Comment by cdutra** [comment]
@drnic You should also see that the deployment config is most likely outdated. What benefit would the `vm_type`tag give to the use? There many other properties that could also be outdated from the cloud-config to what is deployed on the IaaS.

**Comment by dpb587-pivotal** [comment]
Semi-related: https://github.com/cloudfoundry/bosh-cli/pull/351

**Comment by cppforlife** [comment]
@drnic since we will be going after using `vm_resources` i dont think it makes sense to have that functionality in the cpi. i would be open though to show that in the cli's `bosh vms` if available.
