### ISSUE TITLE
[feature] support for network load balancers

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-aws-cpi-release#73]
The new network load balancers have a number of advantages over the classic ELBs, most prominent the option to add the same instance with different ports to the same LB. See http://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html#network-load-balancer-benefits

Can we add support for that LB type, please?

**Comment by cdutra** [comment]
@voelzmo I think this would be a good addition to the AWS CPI.

**Comment by making** [comment]
+1

**Comment by making** [comment]
any chance to be prioritized?

**Comment by dohq** [comment]
+1

**Comment by dpb587-pivotal** [comment]
:link: [Story #157493693](https://www.pivotaltracker.com/story/show/157493693)

**Comment by making** [comment]
@cdutra Great! Which commit resolved this issue? I'd love to try it.
