### ISSUE TITLE
CPI doesn't cope well with rate limit during `describe instance`

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-aws-cpi-release#75]
When a VM is created or deleted, the CPI polls regulary (iirc every 5 seconds) for its state. If you happen to create or delete a *lot* of VMs in parallel, this happens:
```
Task 1504332 | 16:48:27 | Updating instance etcd: etcd/7cb83d59-a9d9-4806-8132-c62f646fccf9 (0) (canary) (00:02:11)
                     L Error: Unknown CPI error 'Unknown' with message 'Request limit exceeded.' in 'delete_vm' CPI method
```

which shows up in the CPI debug log as a problem with `describe instance`, not with the `delete instance` call:
```
D, [2017-12-12T16:49:05.743678 #32102] DEBUG -- [req_id cpi-292807]: Waiting for i-0d1edda4ea71b4ad2 to be terminated, retrying in 16 seconds (4/54)
D, [2017-12-12T16:50:38.489497 #32102] DEBUG -- [req_id cpi-292807]: [Aws::EC2::Client 503 76.74499 8 retries] describe_instances(instance_ids:["i-0d1edda4ea71b4ad2"]) Aws::EC2::Errors::RequestLimitExceeded Request limit exceeded.
```

As you can see, the SDK already tries to retry and backoff:
`[req_id cpi-292807]: [Aws::EC2::Client 503 76.74499 8 retries] describe_instances(instance_ids:["i-0d1edda4ea71b4ad2"]) `, but still fails. The VM actually gets deleted fine, it is just the polling that fails.

I feel like hitting a rate limit during polling should not cause a deployment to fail, but rather cause the CPI to backoff and retry at least one to three times. The action is executed correctly, the CPI is just not able to poll for the state change. 

@cdutra @cppforlife @dpb587-pivotal opinions?

**Comment by dpb587-pivotal** [comment]
I would expect `RequestLimitExceeded` to generally be ignored by the wrappers and to fallback to retry/backoff behavior, whether it's state polling or the underlying actions. Seems like some generic behavior which could be updated in `resource_wait.rb`?

**Comment by voelzmo** [comment]
Seems like the sdk has a built-in waiter feature. Maybe using this would be beneficial? http://docs.aws.amazon.com/sdkforruby/api/

On 21. Dec 2017, at 07:42, Danny Berger <notifications@github.com<mailto:notifications@github.com>> wrote:


I would expect RequestLimitExceeded to generally be ignored by the wrappers and to fallback to retry/backoff behavior, whether it's state polling or the underlying actions. Seems like some generic behavior which could be updated in resource_wait.rb?

**Comment by dpb587-pivotal** [comment]
Generic waiter might be nice if it means less code for us to maintain and it handles limit backoffs.

**Comment by weberstephanhd** [comment]
meanwhile we see this very often. terraform uses throttling and one can set the # of parallel requests and # of retries. What are your plans?

**Comment by voelzmo** [comment]
@belinda-liu We can try to build a dev release and update our production env with it during the next update cycle. This will take ~2 weeks, though.

**Comment by weberstephanhd** [comment]
any news?

**Comment by dpb587-pivotal** [comment]
Closing - the referenced fix is available since [v73](https://github.com/cloudfoundry/bosh-aws-cpi-release/releases/tag/v73) (recently released; I've updated release notes to mention this). If this continues to be an issue, feel free to reopen.
