### ISSUE TITLE
[feature] Spot Requests for longer than 1 week

### ISSUE THREAD

**Issue by jccarte** [cloudfoundry/bosh-aws-cpi-release#76]
Spot instances in bosh would be more useful if we could have longer duration spot requests. The valid_until option is not configurable in the CPI and defaults to 7 days from the request date.

**Comment by cppforlife** [comment]
@jccarte could you point at some aws documentation about this functionality. im not sure i understand your use case. what would you configure this value to?

**Comment by jccarte** [comment]
Ideally we could configure the duration of spot requests. In my specific use I would like to use spot instances for highly available services in my staging environment to save cost. They are generally not rebuilt every week, so setting a monthly duration for the spot instance would allow them to remain spot instances for longer before reverting to on-demand pricing.

The default behavior is 7 days from the request, but it is configurable in the spot instance request:

https://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Types/SpotInstanceRequest.html#valid_until-instance_method
