### ISSUE TITLE
Using publicly accessible AMI for testing

### ISSUE THREAD

**Issue by degaurab** [cloudfoundry/bosh-aws-cpi-release#81]
Hi Team,
Can we use more of the publicly accessible AMI for all the integration tests. It will really help in testing changes locally, also it's sometime difficult to figure out the variables required to change AMIs and other test related variables. 

The doc specifying how to ["Manually run lifecycle tests"](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/master/docs/development.md#manually-run-lifecycle-tests) doesn't list all the variables which can be modified.

Thanks,
Gaurab

**Comment by cdutra** [comment]
@degaurab The idea of the doc is to make it easy to run the integration tests. We could have a advanced section for running integration tests that could list all environment variables. Why do you need to change AMI?
