### ISSUE TITLE
External bosh-director and multi-cpi feature

### ISSUE THREAD

**Issue by karampok** [cloudfoundry/bosh-aws-cpi-release#87]
Hi, 
I am trying to deploy something in AWS using a bosh director that is not located in AWS itself using the multi-cpi feature of bosh. Is that possible?

I am getting an error during `bosh upload-stemcell`  because the bosh-director is not located 
`in the in the same region as configured in the manifest.` [lines](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/cb744e5e02fc2d0ecd8f3a8ed16aca25442034b0/src/bosh_aws_cpi/lib/cloud/aws/cloud.rb#L515-L529)

Thanks!

**Comment by karampok** [comment]
thanks for reply!

Indeed with the light stemcell I do not get this error, but  I am getting a new one
```
| Update stemcell: Uploading stemcell bosh-aws-xen-hvm-ubuntu-trusty-go_agent/3586.26 to the cloud (cpi: CFCR-A) (00:00:22)
                   L Error: CPI error 'Bosh::Clouds::CloudError' with message 'ami-62474689 state is failed, expected available, took 14.604543484s' in 'create_stemcell' CPI method
```

What interaction takes place between the director and the aws during a stemcell upload?

**Comment by dpb587-pivotal** [comment]
@karampok are you getting your stemcells from bosh.io? The error message suggests it is dealing with `ami-62474689`, but that is not an official AMI that we produce for that stemcell.

Network/routing should not be an issue at the stemcell upload stage (since upload stemcell should be talking to AWS API which should require generic internet or, at least, AWS API access). More specifically, I was referring to the fact that when VMs are created in your foreign network, they will need to be communicating with the director so they the director's IP will need to be routable from that foreign VM.

**Comment by karampok** [comment]
Hi @dpb587-pivotal ,

The command I execute is 

```
bosh upload-stemcell --sha1 4cda67b5e0a8d5f27d98cdc546d1e1c8f454e7a7   https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3586.26
```
The error I see is 
```
Error: CPI error 'Bosh::Clouds::CloudError' with message 'ami-bc888957* state is failed, expected available, took 14.586662412s' in 'create_stemcell' CPI method
```
which does not give any information (* ami-bc888957 this is the random name)

Debugging in AWS console, i can see that there is a failure in `copying an ami image` from a public image (`085178109370/BOSH-e9e1ca5f-2da2-473b-a6c8-e146cc35bab6 ami-9eb6b075*`) . That copy is failing with  exact reasoning `Copy image failed with an internal error`. 
(*ami-9eb6b075 this should be an official image, right?)

I suspect that it might be IAM permissions, but not sure.

thx!

**Comment by dpb587-pivotal** [comment]
Thanks - sounds like you may have encryption globally enabled which requires some additional IAM permissions. Can you review [this recommended policy](https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/cb744e5e02fc2d0ecd8f3a8ed16aca25442034b0/docs/iam-policy.json#L34-L54) and see if you need to update your policy for your environment?

**Comment by karampok** [comment]
It does not look like IAM permission because the user has already `ec2:*, kms:*` permission.
The user was created as [bbl recommends](https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/getting-started-aws.md#creating-an-iam-user).

On top, I shortly replaced the creds with my root creds, and the same error occurs.
I tried also the policy you recommended. Maybe I miss something ...

Is there any aws cli equivalent command that takes place during the stemcell upload which will allow me to isolate the error?

For reference the cpi config looks like that
```
Content     cpis:
            - name:CFCR-A
              properties:
                access_key_id: XXXX
                credentials_source: static
                default_security_groups:
                - CFCR-A-bosh-agents-sg
                region: eu-central-1
                secret_access_key: YYYY
              type: aws

```
Thx!

**Comment by karampok** [comment]
it works!

I had to add the following lines to the cpi config

```
encrypted: true
kms_key_arn: arn:aws:kms:eu-central-XXX
```

**Comment by dpb587-pivotal** [comment]
@karampok Glad it is working, but it is still a little curious. By chance, did your AWS account remove the default EC2/EBS encryption key from KMS? Or perhaps deactivate and schedule it for deletion?

**Comment by karampok** [comment]
How can I check if that happened? 
Not very familiar with KMS component.

**Comment by karampok** [comment]
Moving a bit forward, during a `bosh deploy -d x `the compilation vms are failing.
Observing what is happening, I can see that the new vms are trying to contact registry over the internal IP of the director

```
'http://registry:xxxx@10.0.0.6:25777/instances/i-08b9463ae19a916fb/settings' }
```
Can I change the registry in the bosh cpi config (`bosh configs`) instead of the `the bosh.yml` when deploying the bosh director?

Any good practise here, that I am missing?

Thanks!

**Comment by dpb587-pivotal** [comment]
Sorry, missed this reopening. I believe the registry settings can only be configured via AWS release properties, and the `properties` for a CPI from `cpi-config` are only the `aws` properties of the release. So I think you'll need to update `bosh.yml`.

**Comment by mandar14** [comment]
Not sure my issues is 100% related,  I have bosh in AWS account A and I want to deploy lets say CF  across 2 AWS accounts A and B, 

My bosh has role from account A, how can I use IAM profile from account B. 

Will bosh be able to assume role from account  in this case
