### ISSUE TITLE
Add support for r5d instance types

### ISSUE THREAD

**Issue by bandesz** [cloudfoundry/bosh-aws-cpi-release#91]
## What

**Edit**: I reworded the issue to focus only on the r5d instance types and not all the missing ones.

We (GOV.UK PaaS) would like to use the new r5d instance types with instance storage (which also use NVMe).

We forked the repository and added the r5d instance types to the instance storage mapping (`INSTANCE_TYPE_DISK_MAPPING`) in `block_device_manager.rb`.

In the cloud configuration we simply used `use_instance_storage: true`.

When running the bosh deploy we get timeout errors:

```
Task 38317 | 12:36:37 | Creating missing vms: diego-cell/dd227f39-a519-4fec-b8f0-0229e3a2731e (0) (00:11:00)
                     L Error: Timed out pinging to e86db793-3efc-458f-8ad4-d2ec462482bb after 600 seconds
```

I also tried to add the r5d instances to the `requires_nvme_device` function, but got the same timeout.

## Versions

bosh: 268.4.0
bosh-cli: 5.2.1
aws-cpi: v73

**Comment by bandesz** [comment]
Reading some more about this I think we'll only try to add support for the r5d instances.

**Comment by mrosecrance** [comment]
We've made changes to support r5d instances [here](https://github.com/cloudfoundry/bosh-aws-cpi-release/commit/9f2a9cc58dafc547e1f77cbb68b1f0a5ac207208) and there were some bosh-agent changes that happened just before it.
