### ISSUE TITLE
Tag VMs on creation

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-aws-cpi-release#93]
Would it be possible to tag VMs as they are created in the RunInstance API, rather than after the fact?

We are required to lock down the IAM policy bosh gets so that it cannot terminate all instances in the account, and the only feasible way seems to be by allowing it to terminate only vms with a specific tag. However, when bosh has problems creating the vm (a specified ELB doesn't exist for example), the tag isn't yet applied to the VM, and bosh gets an authorization failure when trying to terminate the failed VM.

**Comment by geofffranks** [comment]
This is now becoming a problem for us again in a different way, as we are being required through AWS Service Control Policies to apply tags to our VMs in the RunInstance API calls.

**Comment by h4xnoodle** [comment]
Hi @geofffranks this has been implemented now. It was mostly a bosh director change, as the director is the component that decides when and where to send the tags. The AWS CPI needs to receive them, however.

You'll need AWS CPI [v78+](https://github.com/cloudfoundry/bosh-aws-cpi-release/releases/tag/v78) and director [v270.7.0+](https://github.com/cloudfoundry/bosh/releases/tag/v270.7.0)

The director commit: https://github.com/cloudfoundry/bosh/commit/97a03bfd387a57a7bf417120afcf6730a2dbff62
AWS CPI commit: https://github.com/cloudfoundry/bosh-aws-cpi-release/commit/00e11f480847a4e88533f1e95b7c626a213d780b

Closing, as this is now implemented.
