### ISSUE TITLE
Bad Error propagation for failures encountered when creating VMs

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/bosh-aws-cpi-release#94]
We ran into a situation where we attempt to create a new VM, attach it to an ALB target group (which doesn't exist because of bad config), and then BOSH tries to terminate the instance, but fails due to insufficient permission (see #92). The error we get when BOSH fails the task is that authorization failure for instance termination, rather than either both, or an indication that the ALB target group didn't exist. It took more digging than should be required to figure out why bosh was failing to terminate an instance when the output was that it was creating an instance:

```
Task 1182826 | 20:45:07 | Creating missing vms: haproxy/4d38d8cb-6f6c-4b88-914e-2c901ab72206 (0) (00:00:57)
                     L Error: Unknown CPI error 'Unknown' with message 'You are not authorized to perform this operation. Encoded authorization failure message: REDACTED' in 'create_vm' CPI method (CPI request ID: 'cpi-123977')
```

If anything can be done to show both errors would be much appreciated.

**Comment by xtreme-conor-nosal** [comment]
The CPI error message is what comes back from the IAAS. If AWS deems the contents of the authorization failure message to be too sensitive to log, it would be inappropriate for bosh to automatically decode and log it (assuming it had the additional IAM role required to decode).
