### ISSUE TITLE
Change T2/T3 unlimited

### ISSUE THREAD

**Issue by benjaminguttmann-avtq** [cloudfoundry/bosh-aws-cpi-release#97]
Hi,

Is there a way to enable/disable the unlimited feature for T2/T3 instances via the cloud-config? If not, is it possible to get this feature implemented ?

Thank you.

Greetings,

Benjamin

**Comment by donghoang89** [comment]
+1 

Our T2 instances are also experiencing performance issue without unlimited feature disabled. Currently, we have to manually enable the feature on aws console after deploying the servers with bosh.
