### ISSUE TITLE
AWS SDK polling on instances should use `waiter` instead of immediate `describe_instance`

### ISSUE THREAD

**Issue by videlov** [cloudfoundry/bosh-aws-cpi-release#99]
Based on the recent issues with the AWS EC2 SDK, we have sporadic errors, e.g.:

```
undefined method instances' for nil:NilClass. backtrace: /var/vcap/data/packages/bosh_aws_cpi/86134adddad298a45975f01046f47eab879b7511/vendor/bundle/ruby/2.4.0/gems/aws-sdk-ec2-1.36.0/lib/aws-sdk-ec2/instance.rb:307:in load'
```

From the issue on the Ruby SDK gem:
https://github.com/aws/aws-sdk-ruby/issues/2094

like suggested, it should be better to implement a waiter logic, before start polling `describe_instance` after initial creation:
https://aws.amazon.com/blogs/developer/waiters/

**Comment by jfmyers9** [comment]
Hi @videlov,

We made a change to utilize the waiter before proceeding with other actions when creating an instance. This change should be in `v76`. Let us know if you see any improvement.

Best,

@jfmyers9
